# Feature Engineering - Prediksi Harga Pangan

Tahap ini bertujuan membuat fitur time-series dari dataset harga pangan.

Dataset:
- Provinsi: Jawa Timur
- Komoditas: Beras

Feature yang dibuat:
- lag_1 (harga kemarin)
- lag_7 (harga minggu lalu)
- rolling_mean_7 (rata-rata harga 7 hari)

In [1]:
import pandas as pd

# Load dataset

In [2]:
df = pd.read_csv("../data/processed/harga_clean.csv")

df["Tanggal"] = pd.to_datetime(df["Tanggal"])

df.head()

     Tanggal           Provinsi Komoditas    Nilai NilaiDiff
0 2024-03-01     Sumatera Utara     Beras  13800.0       Rp0
1 2024-03-01        Papua Barat     Beras  15900.0       Rp0
2 2024-03-01   Kalimantan Timur     Beras  15950.0     Rp550
3 2024-03-01  Sulawesi Tenggara     Beras  16100.0       Rp0
4 2024-03-01        DKI Jakarta     Beras  16150.0       Rp0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17607 entries, 0 to 17606
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Tanggal    17607 non-null  datetime64[ns]
 1   Provinsi   17607 non-null  object
 2   Komoditas  17607 non-null  object
 3   Nilai      17607 non-null  float64
 4   NilaiDiff  17607 non-null  object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 687.9+ KB

# Membuat lag fitur

In [8]:
df["lag_1"] = df["Nilai"].shift(1)

df["lag_7"] = df["Nilai"].shift(7)

df["rolling_mean_7"] = df["Nilai"].rolling(7).mean()

df["rolling_std_7"] = df["Nilai"].rolling(7).std()

# Hapus Missing Value

In [9]:
df = df.dropna()

df.head()

,Tanggal,Provinsi,Komoditas,Nilai,NilaiDiff,lag_1,lag_7,rolling_mean_7,rolling_std_7
14,2024-03-01,Kalimantan Tengah,Beras,19500.0,Rp50,18650.0,15900.0,17557.142857,1086.825872
15,2024-03-01,Banten,Beras,16750.0,Rp0,19500.0,16700.0,17564.285714,1080.398956
16,2024-03-01,Bengkulu,Beras,15900.0,Rp0,16750.0,16750.0,17442.857143,1225.230785
17,2024-03-01,Bali,Beras,16700.0,Rp0,15900.0,16900.0,17414.285714,1242.213846
18,2024-03-01,Sulawesi Tengah,Beras,15650.0,Rp0,16700.0,17050.0,17214.285714,1411.770250

# Hail Feature Engineering

In [10]:
df.head(10)

,Tanggal,Provinsi,Komoditas,Nilai,NilaiDiff,lag_1,lag_7,rolling_mean_7,rolling_std_7
14,2024-03-01,Kalimantan Tengah,Beras,19500.0,Rp50,18650.0,15900.0,17557.142857,1086.825872
15,2024-03-01,Banten,Beras,16750.0,Rp0,19500.0,16700.0,17564.285714,1080.398956
16,2024-03-01,Bengkulu,Beras,15900.0,Rp0,16750.0,16750.0,17442.857143,1225.230785
17,2024-03-01,Bali,Beras,16700.0,Rp0,15900.0,16900.0,17414.285714,1242.213846
18,2024-03-01,Sulawesi Tengah,Beras,15650.0,Rp0,16700.0,17050.0,17214.285714,1411.770250
19,2024-03-01,Jawa Barat,Beras,15850.0,Rp0,15650.0,17350.0,17000.000000,1498.888477
20,2024-03-01,Aceh,Beras,13850.0,Rp0,15850.0,18650.0,16314.285714,1702.379287
21,2024-03-01,Sulawesi Selatan,Beras,14050.0,Rp50,13850.0,19500.0,15535.714286,1163.584364
22,2024-03-01,Kepulauan Riau,Beras,14550.0,Rp0,14050.0,16750.0,15221.428571,1074.653876
23,2024-03-01,Nusa Tenggara Barat,Beras,14700.0,Rp0,14550.0,15900.0,15050.000000,1043.631480